HDS-1628 Zooming makes koro svg lines appear bug
City-of-Helsinki/helsinki-design-system pull request #1013
Opened 2023-04-02 14:24 UTC by laitine

## Description

* When the koro SVG shape is rotated or vertically flipped random thin border lines can appear, this fixes such issues for Chrome, Firefox and Safari
* The SVG shapes have been updated to accurately reflect the UI kit and SVG files optimized to improve performance

## Motivation and Context

This fixes the issue with visual integrity of the koro shape when the rotated or vertically flipped and improves consistency by accurately replicating the koro graphic asset designs defined by the brand. 

## How Has This Been Tested?

Manual testing on latest versions of Chrome, Firefox and Safari on a Mac.

## Screenshots (if appropriate):

![Koro issue screenshot](https://user-images.githubusercontent.com/305975/229358777-729013f2-35e8-4434-8fc3-2e2a50fc3379.png)

2023-04-21 10:32 UTC, mikkojamG requested changes
Looks good 👍 Unit tests need snapshots to be updated, possibly also visual tests 🤔

2023-04-25 10:52 UTC, laitine commented on packages/react/src/components/koros/Koros.tsx
> +    wave: <path transform={transform} d="m0 0v85h32v-85l-16 16z" />,
These were aligned to before 3.0 but I can update them to the new naming scheme 👌

2023-04-26 12:25 UTC, laitine commented
Pending official term translations from brand to use for names https://helsinkisolutionoffice.atlassian.net/browse/HDS-1505

2023-04-26 12:29 UTC, harriplappalainen commented on packages/react/src/components/koros/Koros.tsx
> +    wave: <path transform={transform} d="m0 0v85h32v-85l-16 16z" />,
Fixes need to be added to the branch `release-3.0.0`. Also Wave should be Vibration and Storm should be Wave.

2023-05-29 18:25 UTC, laitine commented
Core components also with correct names updated. Snapshot test and visual tests now added.

2023-06-01 06:55 UTC, harriplappalainen approved these changes
Is good! 👍 🥇 Except for the conflicts 😞

2023-07-31 08:19 UTC, laitine commented
Missing implementation for Koros Exact fit in React https://hds.hel.fi/storybook/react/?path=/docs/components-koros--exact-fit

2023-09-26 07:16 UTC, mikkojamG approved these changes

2023-09-26 07:16 UTC, merged