Hds 1850 Header navigation sub menu arrow fix
City-of-Helsinki/helsinki-design-system pull request #1095
Opened 2023-08-28 10:32 UTC by minnas

## Description

This pr fixes closed sub-menu arrow direction based on Figma's design

## Motivation and Context

[HDS-1850](https://helsinkisolutionoffice.atlassian.net/browse/HDS-1850)

## How Has This Been Tested?

Tested locally

## Screenshots (if appropriate):

<img width="365" alt="sub-menu-arrow-right" src="https://github.com/City-of-Helsinki/helsinki-design-system/assets/1567533/ff4b5c8f-6605-4191-b2e6-ccf9a46f25b8">
<img width="365" alt="sub-menu-arrow-left" src="https://github.com/City-of-Helsinki/helsinki-design-system/assets/1567533/3375d0d7-f23d-4a60-9715-a9969453ae74">

2023-08-28 11:09 UTC, timwessman commented
works correctly. Maybe `getPosition: () => DropdownMenuPosition` should be `@internal` prop

2023-08-28 11:14 UTC, timwessman requested changes

2023-08-28 11:14 UTC, timwessman commented on packages/react/src/components/header/components/navigationLink/NavigationLink.tsx
> +    console.log('MENU SIZE', size);
is this still needed?

2023-08-28 11:14 UTC, timwessman commented on packages/react/src/components/header/components/navigationLink/navigationLinkDropdown/NavigationLinkDropdown.tsx
> +  getPosition: () => DropdownMenuPosition;
This could be `@internal`

2023-08-28 11:28 UTC, minnas commented on packages/react/src/components/header/components/navigationLink/NavigationLink.tsx
> +    console.log('MENU SIZE', size);
Removed, added only for testing,

2023-08-30 10:11 UTC, timwessman approved these changes

2023-08-30 10:47 UTC, merged