Hds 2017 header docs fixes
City-of-Helsinki/helsinki-design-system pull request #1194
Opened 2023-12-20 11:41 UTC by harriplappalainen

## Description

Fixes to Header docs such as broken links, missing props.

## Related Issue

https://helsinkisolutionoffice.atlassian.net/browse/HDS-2017

## How Has This Been Tested?
Localhost
[Demo](https://city-of-helsinki.github.io/hds-demo/hds-2017-header-docs-fixes/components/header)

2023-12-21 14:20 UTC, Riippi commented
Header.ActionBar `onMenuButtonClick` should be `onMenuClick` ?

2023-12-21 14:21 UTC, Riippi requested changes

2023-12-22 06:28 UTC, harriplappalainen commented on site/src/docs/components/header/index.mdx
> +**Note:** Header is designed to be used full width at the top of the page above the main content. Preview here might not scale correctly and mobile navigation menu is disabled. <Link openInNewTab ope
Good catch! It seems that storybook controls do not work when passed as URL parameters 🤔 That's weird. Then we can't directly link to dark theme.

2023-12-22 09:46 UTC, NikoHelle commented on site/src/docs/components/header/index.mdx
> +**Note:** Header is designed to be used full width at the top of the page above the main content. Preview here might not scale correctly and mobile navigation menu is disabled. <Link openInNewTab ope
Url params work here: https://hds.hel.fi/storybook/react/?path=/story/components-login--example-application&args=useKeycloak:true

Maybe the issue is with data type or args in the story.

2023-12-22 11:55 UTC, harriplappalainen commented on site/src/docs/components/header/index.mdx
> +**Note:** Header is designed to be used full width at the top of the page above the main content. Preview here might not scale correctly and mobile navigation menu is disabled. <Link openInNewTab ope
Hmm. I added the code below specifically for WithFullFeatures story but to no avail. Behaves as Mikko said.
```
WithFullFeatures.args = {
  theme: 'light',
};
WithFullFeatures.argTypes = {
  theme: {
    defaultValue: 'light',
    options: ['light', 'dark'],
  },
}; 
```

2023-12-22 11:56 UTC, harriplappalainen commented on site/src/docs/components/header/index.mdx
> +**Note:** Header is designed to be used full width at the top of the page above the main content. Preview here might not scale correctly and mobile navigation menu is disabled. <Link openInNewTab ope
People have had [issues](https://github.com/storybookjs/storybook/issues/14508) with this and it might be fixed in Storybook v7.

2023-12-22 13:16 UTC, NikoHelle commented on site/src/docs/components/header/index.mdx
> +**Note:** Header is designed to be used full width at the top of the page above the main content. Preview here might not scale correctly and mobile navigation menu is disabled. <Link openInNewTab ope
Ok. Unfixable then.

2023-12-22 14:10 UTC, Riippi approved these changes

2023-12-27 10:49 UTC, laurakarhu approved these changes
Looking good, thanks!

2023-12-29 09:05 UTC, merged