(HDS-2137) Update new icons to icons list in site
City-of-Helsinki/helsinki-design-system pull request #1226
Opened 2024-02-13 12:16 UTC by mrTuomoK

## Description

Update to icons to site icons list

## Related Issue

[HDS-2137](https://helsinkisolutionoffice.atlassian.net/browse/HDS-2137)

## How Has This Been Tested?

- locally built site

## Add to changelog
- [ ] Added needed line to changelog

2024-02-23 12:39 UTC, NikoHelle commented on CHANGELOG.md
> +- [Icons] document-group icon wrong colors
Capitalise "document"

2024-03-05 06:27 UTC, laurakarhu requested changes
Otherwise good, but wrong version number?

2024-03-05 06:27 UTC, laurakarhu commented on release/icon-kit-template-CHANGELOG.txt
Should be 3.6.0 as 3.5.0 has been released already?

2024-03-05 06:32 UTC, mrTuomoK commented on release/icon-kit-template-CHANGELOG.txt
Nope, it's bumped as we do the next release. (this was accidentally left one version too low last time I guess 🤦 )

2024-03-05 06:33 UTC, mrTuomoK commented on release/icon-kit-template-CHANGELOG.txt
But the new icon-kit -workflow should now handle this better and automatically so it "can't be left behind"

2024-03-05 07:24 UTC, mrTuomoK commented on release/icon-kit-template-CHANGELOG.txt
ping @laurakarhu so all should be ok?

2024-03-05 09:31 UTC, laurakarhu approved these changes
Let's see how the script works in practice

2024-03-05 11:17 UTC, merged