HDS-2147 update icon list on docsite
City-of-Helsinki/helsinki-design-system pull request #1284
Opened 2024-05-06 08:38 UTC by terovirtanen

## Description

Automate adding new icons to docsite

[HDS-2147](https://helsinkisolutionoffice.atlassian.net/browse/HDS-2147)

## Related Issue

Closes #

## Motivation and Context

## How Has This Been Tested?

## Demos:
[Docs](https://city-of-helsinki.github.io/hds-demo/preview_<PR_ID>/)

[Core Storybook](https://city-of-helsinki.github.io/hds-demo/preview_<PR_ID>/storybook/core)

[React Storybook](https://city-of-helsinki.github.io/hds-demo/preview_<PR_ID>/storybook/react)

## Screenshots (if appropriate):

## Add to changelog
- [ ] Added needed line to changelog

2024-05-13 07:43 UTC, NikoHelle requested changes

2024-05-16 06:16 UTC, terovirtanen commented on .github/workflows/hds-demo-preview.yml
> +     # tryout iconlist -script
This is just for testing in the PR and it will be removed before merge.

This should do in update-icon-library.yml only

2024-05-16 07:49 UTC, terovirtanen commented on .github/workflows/hds-demo-preview.yml
> +             jq '.nodes."172:2478".document.children | .[] | {group: .name?, icon: .children[]?.name?}' | \
Fixed to use NODE_ID

This is just for testing in the PR and it will be removed before merge.
This should do in update-icon-library.yml only

2024-05-16 07:50 UTC, terovirtanen commented on .github/workflows/update-icon-library.yml
> +             jq '.nodes."172:2478".document.children | .[] | {group: .name?, icon: .children[]?.name?}' | \
done

2024-05-16 08:11 UTC, terovirtanen commented on .github/workflows/hds-demo-preview.yml
> +      - name: Preview url to PR comment
comment message refactored. How about now?

2024-05-16 08:11 UTC, terovirtanen commented on site/scripts/iconlist.js
> +const icon_groups_json = "./icon_group.json"; // <data from figma-api> | jq '.nodes."172:2478".document.children | .[] | {group: .name?, icon: .children[]?.name?}' | jq -s .> icon_group.json
removed

2024-05-16 08:11 UTC, terovirtanen commented on site/scripts/iconlist.js
> +// const exitError = (msg) => {
removed

2024-05-22 06:41 UTC, NikoHelle commented on site/scripts/iconlist.js
> +//  <data from figma-api> | jq '.nodes."172:2478".document.children | .[] | {group: .name?, icon: .children[]?.name?}' | jq -s .> icon_group.json
This comment seem irrelevant?

2024-05-22 06:42 UTC, NikoHelle commented on site/scripts/iconlist.js
> +    console.log(output)
Is this intentionally left here?

2024-05-22 06:44 UTC, NikoHelle reviewed
Couple of comments about comments and console.log

2024-05-22 07:20 UTC, terovirtanen commented on site/scripts/iconlist.js
> +    console.log(output)
removed

2024-05-22 10:26 UTC, NikoHelle approved these changes

2024-05-23 04:24 UTC, merged