Fix tag props to allow html props
City-of-Helsinki/helsinki-design-system pull request #1288
Opened 2024-05-16 11:24 UTC by mrTuomoK

## Description

Tag did not allow native props when native props were put into props: TagProps

## How Has This Been Tested?

- local machine

## Demos:
[Docs](https://city-of-helsinki.github.io/hds-demo/preview_<PR_ID>/)

[Core Storybook](https://city-of-helsinki.github.io/hds-demo/preview_<PR_ID>/storybook/core)

[React Storybook](https://city-of-helsinki.github.io/hds-demo/preview_<PR_ID>/storybook/react)

## Screenshots (if appropriate):

## Add to changelog
I guess not needed since the whole Tag has been rewritten for v4.0.0

2024-06-03 07:00 UTC, NikoHelle requested changes

2024-06-03 07:00 UTC, NikoHelle commented on packages/react/src/components/tag/Tag.tsx
> +  IntersectType<React.AnchorHTMLAttributes<HTMLAnchorElement>, React.HTMLAttributes<HTMLDivElement>> & {
I'd bet the Div-version is more commonly used. We could also force the devs to give the type when Anchor-version is used:

```
export type TagProps<T = HTMLDivElement|> = CommonProps & React.HTMLAttributes<T> & ....
```

Usage:
```
const divProps: TagProps = {}
const anchorProps: TagProps<HTMLAnchorElement> = {}
```

2024-06-04 07:18 UTC, mrTuomoK commented on packages/react/src/utils/commonProps.ts
> +export type CommonProps = {
Good point, changing...

2024-06-06 07:37 UTC, NikoHelle commented on packages/react/src/components/tag/Tag.tsx
> +  };
Now that there is `<T = HTMLDivElement>` this could simply be

`ref?: React.Ref<T>`

2024-06-10 06:29 UTC, NikoHelle approved these changes
Looks good!

2024-06-10 06:31 UTC, merged