HDS-2275 Login pattern page and documentation
City-of-Helsinki/helsinki-design-system pull request #1295
Opened 2024-06-05 10:47 UTC by nooranen

## Description

- PR for login documentation changes (WIP)

**To do:**
- Still needs checking and more content
- Header component docs
- Login pattern page

 - Correct demos & technical information
 -  Login & Profile pattern page

## Add to changelog
- [ ] Added needed line to changelog

2024-06-14 12:39 UTC, laurakarhu reviewed
Nice job on content!

2024-06-14 12:39 UTC, laurakarhu commented on site/src/docs/components/header/index.mdx
> +    - No more than two ActionBarItems are recommended to use this high priority position, to conserve mobile menu's usability.
It is higly recommended to have maximum 2 ActionBarItems...

2024-06-20 10:14 UTC, Riippi approved these changes
👍

2024-07-01 12:41 UTC, mrTuomoK commented on CHANGELOG.md
> +## [3.9.0] - June, X, 2024
Eh... you mean July? 😄

2024-07-02 06:16 UTC, laurakarhu requested changes
Minor improvements to the readability and some typos

2024-07-02 06:16 UTC, laurakarhu commented on site/src/docs/patterns/login/building-login.mdx
> +Logging in or out of an OIDC server requires browser redirections to the server and back. UI's only show login and logout buttons. No other form elements are needed.
Better readability if we write it open. The user interface only shos login and logout buttons.

2024-07-02 06:16 UTC, laurakarhu commented on site/src/docs/patterns/login/building-login.mdx
> +The `login` call is asyncronous and may fail if the OIDC server is offline or the service URL is not registered. UI's must indicate loading has started, and possible errors must be handled by the UI.
The user interface must indicate that the loading has started

2024-07-02 06:16 UTC, laurakarhu commented on site/src/docs/patterns/login/building-login.mdx
> +Logging out is almost identical to the log-in process. It is also asyncronous and may fail.
Log out is almost identical to the log in process.

2024-07-02 06:16 UTC, laurakarhu commented on site/src/docs/patterns/login/building-login.mdx
> +User information is stored in tokens which are decrypted by the Login system and an user object is provided to UI's. It holds, for example, user's name and email address.
is provided to user interfaces.

2024-07-02 06:16 UTC, laurakarhu commented on site/src/docs/patterns/login/building-login.mdx
> +with the GraphQL module, but it is not used in HDS components. The user object returned by the OIDC server has a `profile`
Link to the GraphlQL module?

2024-07-02 10:56 UTC, laurakarhu approved these changes
These minor tweaks don't prevent release, but should be done in proper moment

2024-07-02 11:45 UTC, merged