Release-4.0.0 HDS-2424 fix mobile title sizes
City-of-Helsinki/helsinki-design-system pull request #1402
Opened 2024-11-04 13:13 UTC by mrTuomoK

## Description

Fixes mobile Hero font-size

## Related Issue

Closes [HDS-2424](https://helsinkisolutionoffice.atlassian.net/browse/HDS-2424)

## How Has This Been Tested?

- running tests

## Demos:

Links to demos are in the comments

## Add to changelog

- [X] Added needed line to changelog

2024-11-04 14:26 UTC, SillanmakiA commented on packages/core/src/components/hero/hero.css
> +    font-size: var(--fontsize-heading-xl);
Specifications were not the clearest. Use --fontsize-heading-xl-mobile also in this breakpoint between 768px and 992px.

2024-11-04 14:27 UTC, SillanmakiA requested changes
Use --fontsize-heading-xl-mobile also in "tablet" breakpoint 768-991px.

2024-11-04 15:25 UTC, mrTuomoK commented
Fixed the issue @SillanmakiA 👍 Although it's not caught by our tests since we only check mobile and desktop sizes but can be tested in the demos ofc.

2024-11-05 07:35 UTC, SillanmakiA approved these changes
It's perfect. 👌🏻

2024-11-06 08:44 UTC, merged