[Documentation] Date and time guidelines
City-of-Helsinki/helsinki-design-system pull request #209
Opened 2020-08-07 10:43 UTC by ronijaakkola

## Description
This PR adds requested date and time guidelines to HDS documentation. Guidelines are located in a new page Guidelines/Data formats. Later on more similar guidelines can be added to the same page.

## How Has This Been Tested?
This has been tested working by running the documentation site locally.

2020-08-10 11:15 UTC, badrange commented on site/docs/guidelines/data_formats.mdx
> +Day, month and year           | 24.6.2020                              | 24/06/2020                                           | Note that English locale uses MM/DD/YYYY format rather than DD/MM/YYYY.
Ymmärtääkseni on tarkoitus käyttää suomi-pvm-locale myös englanniksi koska palvelu on Suomessa ja voimme olettaa että kaikki täällä asuvat ovat tottuneet siihen.

2020-08-10 12:23 UTC, ronijaakkola commented on site/docs/guidelines/data_formats.mdx
> +Day, month and year           | 24.6.2020                              | 24/06/2020                                           | Note that English locale uses MM/DD/YYYY format rather than DD/MM/YYYY.
@badrange Eli periaatteessa tuo "Format in English" -sarake olisi siis turha?

2020-08-10 12:33 UTC, ronijaakkola commented on site/docs/guidelines/data_formats.mdx
> +Day, month and year           | 24.6.2020                              | 24/06/2020                                           | Note that English locale uses MM/DD/YYYY format rather than DD/MM/YYYY.
Ja päteekö tämä sekä aikoihin että päivämääriin? Eli vaikka kieli olisi englanti, niin kellonajat Suomen muodossa (esim. 15:00) ja päivämäärät myös (esim. 24.6.2020)?

2020-08-12 09:34 UTC, ronijaakkola commented
Poistin englannin localen esimerkit kokonaan ja muutin hieman tekstejä tukemaan tätä.

2020-08-31 10:03 UTC, eemelinieminen requested changes
Esimerkeissä yksi pikkufiba. Muuten hyvä pohja rakentaa data formats -dokumentaatiota!

2020-08-31 10:03 UTC, eemelinieminen commented on site/docs/guidelines/data_formats.mdx
> +Time (in text)                  | 15.00, 2:00                   | When presenting times in written text, use single dot instead of colon separator. Leading zeros can be opted out as well. 24-hour clo
_Format_ column 2:00 > 2.00

2020-08-31 12:12 UTC, ronijaakkola commented on site/docs/guidelines/data_formats.mdx
> +Time (in text)                  | 15.00, 2:00                   | When presenting times in written text, use single dot instead of colon separator. Leading zeros can be opted out as well. 24-hour clo
Fixed.

2020-08-31 12:50 UTC, eemelinieminen approved these changes

2020-09-08 04:54 UTC, merged