[Change] Documentation site screenshot update
City-of-Helsinki/helsinki-design-system pull request #234
Opened 2020-09-02 11:52 UTC by ronijaakkola

## Description
This PR replaces old Abstract and Sketch screenshots in the **For designers** documentation page.
- Images are now equally sized
- All images are full application screenshots, no cropping used
- User names and project names were removed/hidden from all screenshots

PR also adds image set for an (possibly) upcoming tutorial for importing projects to Abstract. It made sense to make these at the same time to achieve better consistency between screenshots.

## How Has This Been Tested?
Tested running the documentation site locally.

2020-09-02 12:51 UTC, eemelinieminen requested changes
Löytyi yksi väärä kuva ja pari pientä parannusehdotusta.

2020-09-02 12:51 UTC, eemelinieminen commented on site/docs/get_started/for_designers.mdx
> +<Image src="../../static/fordesigners-abstract-link-libraries.png " alt="Linking HDS master libraries" style="max-width:75%" viewable/>
Prosentuaalinen max-width tekee kuvista kapeita pienellä ruudulla, olisko parempi rajoittaa kokoa vain isoilla ruuduilla esim. `style="width:100%; max-width:850px"`

2020-09-02 12:51 UTC, eemelinieminen commented on site/docs/get_started/for_designers.mdx
> +<Image src="../../static/fordesigners-component-insert.png" alt="Inserting component from Components tab" style="max-width:75%" />
Jostain syystä vaihtoehdossa 2 on sama kuva kuin vaihtoehdossa 1. (tiedostonimet kuitenkin eri)
Esimerkkikuvassa pitäisi näkyä valinta sivupalkin Components välilehdeltä, mutta siinä on lisääminen insert pudotusvalikosta.

2020-09-02 12:51 UTC, eemelinieminen commented on site/docs/get_started/for_designers.mdx
> +<Image src="../../static/fordesigners-component-overrides.png" alt="Customising symbol overrides" style="max-width:75%" viewable/>
Näihin kuviin, joissa puhutaan tietystä sivupalkin osiosta vois lisätä jonkun focus-henkisen korostuksen mistä kohdasta ruutua puhutaan (esim. tässä koko Overrides-osio). Nyt huomio kiinnittyy isoon nappiin keskellä.

2020-09-07 09:40 UTC, ronijaakkola commented on site/docs/get_started/for_designers.mdx
> +<Image src="../../static/fordesigners-abstract-link-libraries.png " alt="Linking HDS master libraries" style="max-width:75%" viewable/>
✅

2020-09-07 09:40 UTC, ronijaakkola commented on site/docs/get_started/for_designers.mdx
> +<Image src="../../static/fordesigners-component-insert.png" alt="Inserting component from Components tab" style="max-width:75%" />
✅

2020-09-07 10:10 UTC, ronijaakkola commented on site/docs/get_started/for_designers.mdx
> +<Image src="../../static/fordesigners-component-overrides.png" alt="Customising symbol overrides" style="max-width:75%" viewable/>
✅

2020-09-07 10:27 UTC, eemelinieminen approved these changes
Näyttää hyvältä ja huomattavasti selkeämmältä kuin aikaisemmin

2020-09-07 12:18 UTC, merged