[Content] Design contribution: Sketch file guidelines
City-of-Helsinki/helsinki-design-system pull request #244
Opened 2020-09-11 13:11 UTC by eemelinieminen

## Description
Added Guidelines for HDS library Sketch file naming and structure in doc site Contribution section.

- Added example images to naming guidelines
- Changed Contribution section from single file to four separate files: 
  - Before contribution
  - Design
  - Implementation
  - Documentation. 
- Added LargeParagraph intro texts to new Contribution sub-pages 
- Changed docz theme _inlineCode_ styling
- Changed docz theme _hr_ margins
- Changed docz theme _blockquote_ style to be used as a container for text + image examples
- Changed _Before contribution_ guidelines content

## How Has This Been Tested?
Tested by running the documentation site locally.

2020-09-14 10:15 UTC, ronijaakkola requested changes
Hyvältä näyttää. En oikeastaan ottanut enää sisältöön kantaa, koska olen kommentoinut sitä jo aikaisemmin. Lähinnä korjausehdotuksia kirjoitusvirheisiin ja asetteluun.

2020-09-14 10:15 UTC, ronijaakkola commented on site/docs/Contributing/design.mdx
> +- **Naming language** is British English (except colour names, that follow the brand guidelines).
> (except colour names, that follow the brand guidelines).

Pilkku pois "that" -sanan edestä.

2020-09-14 10:15 UTC, ronijaakkola commented on site/docs/Contributing/design.mdx
> +    This checklist is (in most parts) also available as a <Link href="https://www.sketch.com/extensions/assistants/" external>Sketch Assistant</Link>, that automatically runs a preflight check for Sk
> This checklist is (in most parts) also available as a Sketch Assistant, that automatically runs a preflight check for Sketch files.

Pilkku pois "that" -sanan edestä.

2020-09-14 10:15 UTC, ronijaakkola commented on site/docs/Contributing/design.mdx
> +    For more informationb see the <Link href="https://github.com/ronijaakkola/hds-assistant" external>HDS Assistant Github page</Link>. You can also <Link href="sketch://add-assistant?url=https://git
> For more information~~b~~

2020-09-14 10:15 UTC, ronijaakkola commented on site/docs/Contributing/design.mdx
> +    For more informationb see the <Link href="https://github.com/ronijaakkola/hds-assistant" external>HDS Assistant Github page</Link>. You can also <Link href="sketch://add-assistant?url=https://git
> download and install the HDS assistant

Laittaisin "add HDS Assistant directly to Sketch via pressing this link" - tai jotain vastaavaa.

2020-09-14 10:15 UTC, ronijaakkola commented on site/docs/Contributing/design.mdx
> +import { AlertCircle } from "hds-react";
> import { AlertCircle } from "hds-react";

Ylimääräinen import.

2020-09-14 10:15 UTC, ronijaakkola commented on site/docs/Contributing/design.mdx
> +> **Example: Two levels of *types* in Colour *category***
>**Example: Two levels of *types* in Colour *category*** 

Mun silmään nämä kuvien otsikot ovat piirun verran liian lähellä kuvan yläreunaa. En tosin tiedä onko tälle kovin helposti tehtävissä mitään.

2020-09-14 10:15 UTC, ronijaakkola commented on site/docs/Contributing/design.mdx
> +  - ❇️ **[SECTION NAME]** can be used to highlight _sections_ (for example `❇️ NAVIGATION`).
> ❇️ **[SECTION NAME]** can be used to highlight _sections_ (for example `❇️ NAVIGATION`).

Tässä emoji ei renderöidy kooditagien sisällä emojina. Ehkä pitää jättää kooditagien ulkopuolelle se.

2020-09-14 10:23 UTC, eemelinieminen commented on site/docs/Contributing/design.mdx
> +---
Olin korjannut tämän antamalla hr:lle marginaalit style.js:ssä, mutta se oli pudonnut. Nyt pitäisi olla kunnossa.

2020-09-14 10:29 UTC, eemelinieminen commented on site/docs/Contributing/design.mdx
> +  - ❇️ **[SECTION NAME]** can be used to highlight _sections_ (for example `❇️ NAVIGATION`).
hmm… mulla näky oikein kooditägin sisälläkin, tosin rivittyy huonosti, minkä korjasin.

2020-09-14 10:34 UTC, eemelinieminen commented on site/docs/Contributing/design.mdx
> +> **Example: Two levels of *types* in Colour *category***
korjasin blockquoten paddingeja

2020-09-14 11:57 UTC, ronijaakkola commented on site/docs/Contributing/design.mdx
> +  - ❇️ **[SECTION NAME]** can be used to highlight _sections_ (for example `❇️ NAVIGATION`).
Kyllä tämä nyt uusimmassa buildissa näyttäisi toimivan minullakin. Ok siis.

2020-09-14 11:58 UTC, ronijaakkola commented on site/docs/Contributing/design.mdx
> +> **Example: Two levels of *types* in Colour *category***
<img width="547" alt="Screenshot 2020-09-14 at 14 58 18" src="https://user-images.githubusercontent.com/4214671/93083106-c0e74580-f69a-11ea-95ca-de9b684e7c80.png">

On tuo väli mielestäni edelleen aika tiukka.

2020-09-14 11:59 UTC, ronijaakkola commented on site/docs/Contributing/design.mdx
> +---
Uusimmassa buildissa näyttää hyvältä 👍

2020-09-15 08:33 UTC, eemelinieminen commented on site/docs/Contributing/design.mdx
> +> **Example: Two levels of *types* in Colour *category***
Ah joo. Väärinymmärrys. Viilailin vain koko blockquoten paddingeja. 

Blockquoten sisällä oli laitettu p-tagille marginiksi 0. Viilailin nyt p, ul, ol ja img -tagien marginaaleja kauttaaltaan. Tosin jostain syystä linkin sisällä olevien kuvien marginaalit ei muutu… todennäköisesti sama fiba kuin h-tagien kanssa.

2020-09-15 09:17 UTC, ronijaakkola approved these changes
Looks good to go!

2020-09-15 10:08 UTC, merged