[Accessibility] Button fixes
City-of-Helsinki/helsinki-design-system pull request #274
Opened 2020-10-12 12:33 UTC by aleksik

WIP - Requires https://helsinkisolutionoffice.atlassian.net/browse/HDS-449

## Description

Accessibility fixes for the Button component:

- Set button minimum width and height to 44px
- Require `iconLeft` or `iconRight` for supplementary button

## How Has This Been Tested?

Tested locally on Storybook

2020-10-13 11:52 UTC, ronijaakkola commented
Since mobile navigation uses a supplementary button as a "sign out" button, we need to add an icon to it to comply with this new requirement. 

The icon we should use is `signout`.

![image](https://user-images.githubusercontent.com/4214671/95856930-7e7d5b00-0d63-11eb-9e85-d344111ec1c9.png)

2020-10-13 12:00 UTC, niglu1 approved these changes
👍

2020-10-14 12:21 UTC, ronijaakkola commented
@aleksik Documentation was done in this branch. We could merge these together.
https://github.com/City-of-Helsinki/helsinki-design-system/pull/262

2020-10-15 05:48 UTC, aleksik commented
@ronijaakkola I cherry-picked your documentation commit to this branch.

#262 can now be closed.

2020-10-15 06:36 UTC, ronijaakkola commented
> @ronijaakkola I cherry-picked your documentation commit to this branch.
> 
> #262 can now be closed.

Thanks! I will check the documentation and update the examples if needed.

2020-10-21 07:56 UTC, niglu1 requested changes
I noticed that the size and margins of the small button icons are wrong. According to the button design, the size should be the same as for the normal button. The margin between the label and the left/right icons should be 8px, now it's 12px, so it should be changed to use the `var(--spacing-2-xs)` token. Maybe that could be changed as part of this task as we're changing the small button appearance anyway?

```css
/* left - small */
.hds-button--small .hds-icon {
  height: 1.125em;
  margin-left: var(--spacing-xs);
  width: 1.125em;
}
```

2020-10-29 12:46 UTC, ronijaakkola approved these changes

2020-10-29 13:04 UTC, niglu1 approved these changes

2020-10-29 13:04 UTC, merged