[Change] Update color token names and values
City-of-Helsinki/helsinki-design-system pull request #282
Opened 2020-10-20 13:36 UTC by aleksik

## Description

This PR implements changes to color token names and values documented in #280.

Changed token name coat-of-arms-blue > coat-of-arms
Changed token name coat-of-arms-gold > gold
Changed token name coat-of-arms-silver > silver
Changed token names -dark-50 > -dark
Changed token names -light-20 > -light
Changed token names -light-50 > -medium-light
Replaced tokens -light-05 with -light

Changed colour values of light, medium-light, and dark tokens:
--color-brick-light to #ffeeed
--color-brick-medium-light to #facbc8
--color-brick-dark to #800e04
--color-bus-light to #f0f0ff
--color-bus-medium-light to #ccccff
--color-bus-dark to #00005e
--color-coat-of-arms-light to #e6f4ff
--color-coat-of-arms-medium-light to #b5daf7
--color-coat-of-arms-dark to #005799
--color-gold-light to #f7f2e4
--color-gold-medium-light to #e8d7a7
--color-gold-dark to #9e823c
--color-copper-light to #cffaf1
--color-copper-medium-light to #9ef0de
--color-copper-dark to #00a17d
--color-engel-light to #fff9db
--color-engel-medium-light to #fff3b8
--color-engel-dark to #dbc030
--color-fog-light to #e8f3fc
--color-fog-medium-light to #d0e6f7
--color-fog-dark to #72a5cf
--color-metro-light to #ffeee6
--color-metro-medium-light to #ffcab3
--color-metro-dark to #bd2f00
--color-summer-light to #fff4d4
--color-summer-medium-light to #ffe49c
--color-summer-dark to #cc9200
--color-suomenlinna-light to #fff0f7
--color-suomenlinna-medium-light to #ffdbeb
--color-suomenlinna-dark to #e673a5
--color-tram-light to #dff7eb
--color-tram-medium-light to #a3e3c2
--color-tram-dark to #006631

Added new color values:
--color-silver-light: #f7f7f8
--color-silver-medium-light: #efeff0
--color-silver-dark: #b0b8bf

## How Has This Been Tested?

Tested locally on Storybook.

2020-10-21 06:27 UTC, eemelinieminen commented
Toppen! Pitäiskö dokumentaatiomuutokset (https://github.com/City-of-Helsinki/helsinki-design-system/pull/280) yhdistää tähän samaan? Ois sekä väriarvojen että dokumentaation tsekkaaminen helpompaa ja varmempaa :)

2020-10-21 06:59 UTC, aleksik commented
> Toppen! Pitäiskö dokumentaatiomuutokset (#280) yhdistää tähän samaan? Ois sekä väriarvojen että dokumentaation tsekkaaminen helpompaa ja varmempaa :)

Toki! Yhdistän.

2020-10-21 11:02 UTC, eemelinieminen requested changes
Muutama token value oli jäänyt vaihtamatta. Kommenteissa oikeat hexat.

Dokumentaatiota en tarkistanut, muuten kuin että värikoodien pitäisi olla taulukoissa oikein. Roni voisi vielä vilkaista sen läpi.

2020-10-21 13:56 UTC, eemelinieminen approved these changes
Token valuet nyt nopeella vilkaisulla OK. 

Dokumentaatioon oli vielä jäänyt kirjotusvirheitä, minkä takia token esimerkit eivät näkyneet. Fixasin ne dokumentaatiobranchiin ("ligh" muutettu "light")

2020-10-22 08:28 UTC, ronijaakkola approved these changes
Katsoin dokumentaation läpi ja vaikuttaa hyvältä. Ainoa asia, jonka bongasin oli, että tokenit on sivun alalaidan taulukossa hieman epäloogisessa järjestyksessä: Base -> Light -> Medium light. Mutta ei tällä oikeastaan ole mitään merkitystä.

2020-10-23 12:14 UTC, niglu1 approved these changes
👍

2020-10-23 12:17 UTC, merged