[Feature] Koros as core components
City-of-Helsinki/helsinki-design-system pull request #318
Opened 2020-11-16 13:50 UTC by aleksik

## Description

This PR implements Koros as core components.

## How Has This Been Tested?

Tested locally in Storybook

2020-11-17 12:43 UTC, ronijaakkola commented on packages/core/src/components/koros/koros.stories.js
> +export const Storm = () => `
Huomasin, että nämä storyt ovat Reactin ja Coren Storybookissa hieman eri tavalla nimetty ja eri järjestyksessä. En tiedä onko tällä kamalasti merkitystä, mutta jos tuolle ei ole erityistä syytä, niin ne voisi yhtenäistää. Samat kirjoitusasut ja samassa järjestyksessä siltä osin kuin ovat samaa tavaraa.

Esim. "Horizontally flipped" vs "Flipped", Reactista puuttuu "Custom color" kokonaan, muodot ovat hieman eri järjestyksessä (voisi seurata vaikka dokumentaatiosivun ja Sketchin järjestystä basic, beat, pulse ,wave, storm).

2020-11-17 12:44 UTC, ronijaakkola requested changes
Lisäsin ylle pienen korjausehdotuksen Storybookin storyihin.

2020-11-17 12:44 UTC, ronijaakkola commented
Päivitän dokumentaation tähän branchiin myös.

2020-11-17 13:40 UTC, aleksik commented on packages/core/src/components/koros/koros.stories.js
> +export const Storm = () => `
Hyvä huomio!

Päivitin storyt yhtenäisiksi kirjoitusasun ja järjestyksen osalta. Lisäsin myös reactin puolelle "Custom color" -storyn.

2020-11-23 08:47 UTC, ronijaakkola approved these changes

2020-11-24 10:19 UTC, merged