Use fill-icon in text-field error and success texts
City-of-Helsinki/helsinki-design-system pull request #425
Opened 2021-04-19 14:23 UTC by minevala

## Description
- Replace TextArea's and TextInput's error and success text icons with fill-icons.

## Closes
- https://helsinkisolutionoffice.atlassian.net/browse/HDS-577

## How Has This Been Tested?
- Locally on dev's machine

## Screenshots (if appropriate):
<img width="443" alt="Näyttökuva 2021-4-19 kello 17 12 13" src="https://user-images.githubusercontent.com/1610860/115251385-2caef680-a133-11eb-99c3-9a40d6865e58.png">
<img width="456" alt="Näyttökuva 2021-4-19 kello 17 12 04" src="https://user-images.githubusercontent.com/1610860/115251389-2de02380-a133-11eb-89b6-25a1c1f7762e.png">
<img width="457" alt="Näyttökuva 2021-4-19 kello 17 11 47" src="https://user-images.githubusercontent.com/1610860/115251392-2e78ba00-a133-11eb-8c7e-e598abb997bf.png">
<img width="450" alt="Näyttökuva 2021-4-19 kello 17 11 38" src="https://user-images.githubusercontent.com/1610860/115251393-2e78ba00-a133-11eb-928d-6d6330aead13.png">

👉 [Storybook demo](https://city-of-helsinki.github.io/hds-demo/text-field-fill-icons/?path=/story/components-textarea--invalid)

2021-04-20 06:42 UTC, ronijaakkola requested changes
Seems to be working in all inputs. Error state is also used in SelectionGroup component so we probably should add fill icon to that as well.

![image](https://user-images.githubusercontent.com/4214671/115349525-a212d980-a1bc-11eb-9cd5-4fa5eac54c35.png)

2021-04-20 08:32 UTC, VilleMiekkoja approved these changes
Nice 🏅

2021-04-20 10:05 UTC, ronijaakkola approved these changes

2021-04-21 05:33 UTC, laurakarhu approved these changes

2021-04-29 06:49 UTC, merged