Release 1.0
City-of-Helsinki/helsinki-design-system pull request #437
Opened 2021-04-28 12:08 UTC by ronijaakkola

## Description
Updating Roadmap, What's new section and adding changelogs for the 1.0 release.

## How Has This Been Tested?
Tested by running the documentation site locally.

2021-04-28 12:18 UTC, laurakarhu commented on site/docs/about/roadmap.mdx
> +- **HDS 1.0 release 24.04.2021**
29.4.2021 (Correct date and HDS date format)

2021-04-28 12:20 UTC, laurakarhu requested changes
Date needs fixing, otherwise all good.

2021-04-29 06:23 UTC, minevala reviewed
A language tool finding.

2021-04-29 06:23 UTC, minevala commented on site/docs/about/new.mdx
> +- **Removed**: Previously deprected Dropdown component
deprecated

2021-04-29 11:51 UTC, minevala approved these changes

2021-04-29 12:00 UTC, laurakarhu approved these changes
Good job!

2021-04-29 12:01 UTC, merged