Create checkboxs-radiobuttons-toggles.mdx
City-of-Helsinki/helsinki-design-system pull request #518
Opened 2021-08-17 09:48 UTC by laurakarhu

First version of the guide presenting how to choose between checkboxes, radiobuttons and toggles.

## Description

Guide describes in more detail what components checkbox, radiobutton and toggle are most suitable for.

## Related Issue

Closes #

## Motivation and Context

## How Has This Been Tested?
Locally running docsite.

## Screenshots (if appropriate):

2021-09-02 13:56 UTC, minevala reviewed
Nice 👍 
I could help with improving the togglebutton example if needed.

2021-09-02 13:56 UTC, minevala commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +# Checkboxes, radio buttons or toggles?
Checkboxes, radio buttons, or toggles?

2021-09-02 13:56 UTC, minevala commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +An application can use radio buttons when there is a list of two or more mutually exclusive choices and the user needs to select one of them. After clicking the non-selected radio button, whatever wa
My language tool did not like the sentence "But modern website design challenged.." but I'm not sure if there is anything wrong 🤔 
Would it be better as "But the modern web design challenged.."

2021-09-02 13:56 UTC, minevala commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +Radio buttons have lower cognitive load than drop-down menu’s because they make all options permanently visible so that users can easily compare them. Radio buttons are also easier to operate for use
Radio buttons have **a** lower cognitive load than drop-down **menus**

2021-09-02 13:56 UTC, minevala commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +<Playground>
Maybe we could change the theme of the example or something when the user uses the toggle button. Then it would be in line with the guideline text.

2021-09-03 08:02 UTC, laurakarhu commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +# Checkboxes, radio buttons or toggles?
- [ x] add comma

2021-09-03 08:06 UTC, laurakarhu commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +Radio buttons have lower cognitive load than drop-down menu’s because they make all options permanently visible so that users can easily compare them. Radio buttons are also easier to operate for use
- [x] added article

2021-09-03 10:09 UTC, minevala approved these changes
Nice job 🏅

2021-09-07 06:50 UTC, ronijaakkola requested changes
Added a few small comments.

2021-09-07 06:50 UTC, ronijaakkola commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +<b>Example use:</b> Binary choices like YES/NO, agegroup or other similar choices that exclude other options.
> agegroup

age group

2021-09-07 06:50 UTC, ronijaakkola commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +<Link href="https://www.nngroup.com/articles/checkboxes-vs-radio-buttons/" external>Checkboxes vs. Radio Buttons, N&N Group</Link>
These links should be put into a list to maintain consistency between other pages.

2021-09-07 06:50 UTC, ronijaakkola commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +<Link href="../components/checkbox" >HDS checkbox component</Link>
> HDS checkbox component

To be consistent: "HDS Checkbox component documentation"

2021-09-07 06:50 UTC, ronijaakkola commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +<Link href="../components/radio-button" >HDS radio button component</Link>
> HDS radio button component

To be consistent: "HDS Radio button component documentation"

2021-09-07 06:50 UTC, ronijaakkola commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +<Link href="../components/toggle">HDS toggle component</Link>
> HDS toggle component

To be consistent: "HDS Toggle component documentation"

2021-09-07 06:50 UTC, ronijaakkola commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +Radio buttons have a lower cognitive load than drop-down menu’s because they make all options permanently visible so that users can easily compare them. Radio buttons are also easier to operate for u
> menu’s

menus

2021-09-07 06:50 UTC, ronijaakkola commented on site/docs/guidelines/checkboxs-radiobuttons-toggles.mdx
> +Radio buttons have a lower cognitive load than drop-down menu’s because they make all options permanently visible so that users can easily compare them. Radio buttons are also easier to operate for u
> drop-down

HDS documentation uses the format "dropdown" more commonly.

2021-09-07 06:51 UTC, ronijaakkola commented
Should a link to this guideline to be added to Checkbox, Radio button and Toggle documentation pages? Now many people may easily miss it.

2021-09-07 09:17 UTC, ronijaakkola approved these changes

2021-09-07 09:23 UTC, merged