Set Fieldset, File Input, Link, Number Input, Password Input and Phon…
City-of-Helsinki/helsinki-design-system pull request #649
Opened 2022-02-14 15:19 UTC by minevala

…e Input as stable components

## Description
- Set Fieldset, File Input, Link, Number Input, Password Input, and Phone Input as stable components
- Time input and Toggle Input are on the borderline 

Closes #
- https://helsinkisolutionoffice.atlassian.net/browse/HDS-1005

## Motivation and Context
- It gives more confidence for HDS library user if there is fewer draft components

## How Has This Been Tested?
- locally on dev machine

2022-02-15 11:14 UTC, VilleMiekkoja approved these changes
Important update, thanks 👍

2022-02-21 10:33 UTC, ronijaakkola requested changes

2022-02-22 10:33 UTC, minevala commented on site/docs/components/component_overview.mdx
> +[Link](/components/link)                                         | <StatusLabel type="info">Stable</StatusLabel>        | [<IconCheck/>](/storybook/core/?path=/story/components-link--default)
Ok, we can withdraw

2022-02-22 10:34 UTC, minevala commented on site/docs/components/component_overview.mdx
> +[File input](/components/file-input)                             | <StatusLabel type="info">Stable</StatusLabel>        |
We have no users in analytics. We can withdraw this as well

2022-02-22 11:55 UTC, minevala commented on site/docs/components/component_overview.mdx
> +[Link](/components/link)                                         | <StatusLabel type="info">Stable</StatusLabel>        | [<IconCheck/>](/storybook/core/?path=/story/components-link--default)
- [x] Link moved back to draft

2022-02-22 11:55 UTC, minevala commented on site/docs/components/component_overview.mdx
> +[File input](/components/file-input)                             | <StatusLabel type="info">Stable</StatusLabel>        |
- [x] File Input moved back to draft

2022-02-22 12:30 UTC, ronijaakkola approved these changes

2022-02-22 12:34 UTC, merged