Feature/version in new docs
City-of-Helsinki/helsinki-design-system pull request #752
Opened 2022-06-09 15:41 UTC by minevala

## Description
- Add version badge into new site Navigation

## Related Issue
- https://helsinkisolutionoffice.atlassian.net/browse/HDS-1320

## Motivation and Context
- Library users can be verify that they are using the correct version 

## How Has This Been Tested?
- locally on dev machine

## Screenshots (if appropriate):
<img width="578" alt="Screenshot 2022-06-09 at 18 38 57" src="https://user-images.githubusercontent.com/1610860/172888354-eddfb337-2b11-4e56-97d9-6b9c25cffc07.png">
<img width="2" alt="Screenshot 2022-06-09 at 18 38 54" src="https://user-images.githubusercontent.com/1610860/172888368-cb85cc63-d595-4db8-8c58-3f53ecc4a5cb.png">
<img width="650" alt="Screenshot 2022-06-09 at 18 38 48" src="https://user-images.githubusercontent.com/1610860/172888369-ce5228b5-a3e3-4bc5-9034-d61624cb48f9.png">

2022-06-13 12:27 UTC, ronijaakkola requested changes

2022-06-14 12:58 UTC, minevala commented on new-site/src/components/layout.scss
> +  margin-left: var(--spacing-l);
- [ ] fix tag margins

2022-06-14 13:06 UTC, minevala commented
The image alt text is: "GitHub release (latest SemVer)"

2022-06-15 11:25 UTC, ronijaakkola approved these changes

2022-06-16 12:14 UTC, merged