Combobox scroll bug fix
City-of-Helsinki/helsinki-design-system pull request #866
Opened 2022-11-03 13:26 UTC by harriplappalainen

## Description

Combobox automatically scrolls to hovered menu items. This creates a confusing user experience when user scrolls down the list and (accidentally or not) moves the mouse up and the Combobox keeps scrolling even if user didn't mean to. I think this functionality is more trouble than it's worth.

## Related Issue

https://helsinkisolutionoffice.atlassian.net/browse/HDS-1210

## Motivation and Context

People in the Jira ticket's comments and Slack are waiting for us to fix the behaviour.

## How Has This Been Tested?
Locally on dev machine.
[Demo](https://city-of-helsinki.github.io/hds-demo/combobox-scroll-fix/?path=/story/components-dropdowns-combobox--multi-select-example)

2022-11-04 07:52 UTC, tuomashatakka requested changes
Seems to be working well on any viable browser. However, enter Safari...:

Safari still has a minor issue with the dropbox jumping slightly (and losing focus) when the scrollbar is dragged with a mouse.

Steps to reproduce:

1. Select one or more items from the list
2. Try to move the scroll position by dragging the scrollbar with the cursor.

![safari-combobox-probelma](https://user-images.githubusercontent.com/5794328/199920576-b5f03f5e-f793-4e12-b50a-a61e818551c9.gif)

2022-11-07 06:17 UTC, harriplappalainen commented
That is an annoying little bug. I could only get it fixed by adding onMouseDown event listener on the menu's parent div which sets the input focus after a 50ms time out (!!) but then it breaks the component other browsers 😆 As timeouts are nasty hack fixes already I wouldn't want to add a flimsy browser check as well (so as to only do the timeout on Safari). I'm inclined to let this one slide and make a ticket about it to fix it later because the bug exists on production release already and this PR's fix is eagerly anticipated by users. What do you think?

2022-11-07 07:22 UTC, minevala commented
Does Select component have similar issues?
I think we could check that as well if the fix is this simple 👍

2022-11-07 07:46 UTC, harriplappalainen commented
>Does Select component have similar issues?
No, Select all fine & dandy. It didn't use onHighlightedChange which was causing the problem. And it doesn't have Safari issues either.

2022-11-07 12:32 UTC, harriplappalainen commented
@tuomashatakka The safari problem has been fixed and can be tested in the demo.

2022-11-07 13:45 UTC, minevala approved these changes
It works nicely. A good little fix 🎉

2022-11-09 07:29 UTC, tuomashatakka approved these changes

2022-11-09 09:22 UTC, merged